//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public Tbl_User()
        {
            this.Tbl_Ticket = new HashSet<Tbl_Ticket>();
        }
    
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Email { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Tbl_Role Tbl_Role { get; set; }
        public virtual ICollection<Tbl_Ticket> Tbl_Ticket { get; set; }
    }
}
