//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Role
    {
        public Tbl_Role()
        {
            this.Tbl_User = new HashSet<Tbl_User>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleTitle { get; set; }
    
        public virtual ICollection<Tbl_User> Tbl_User { get; set; }
    }
}
